environment:
  name: test
  project: cdf-bootcamp-47-test
  type: test
  selected:

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-47-test
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env

      # Groups
      # OBJECT ID FOR test/prod Groups
      data_developer_source_id: 2128fbbe-2e93-4100-9ccf-891315a4e6b5
      data_pipeline_oee_source_id: aec5e904-bae5-44c5-9084-982c8e1a0539
      readwrite_source_id: 586e4b85-8e0f-4711-9db9-3261b08b6efc
      icapi_extractors_source_id: 9f9cb9cd-e97f-408e-8f08-6c4e1bc0decb

      # Client Ids (App registrations or Service Principals)
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      oee_space_name: oee_ts_space 
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
